name: post_clean_arch
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

   # dio 
  dio: ^5.8.0+1

  # dio Logger 
  pretty_dio_logger: ^1.4.0

  # get it
  get_it: ^8.0.3

  # injectable
  injectable: ^2.5.0

  # json annotation 
  json_annotation: ^4.9.0

  # provider 
  provider: ^6.1.5

  # firebase
  firebase_core: ^3.14.0

  # firebase auth
  firebase_auth: ^5.6.0

  # cloud firestore
  cloud_firestore: ^5.6.9

  # code nest ui
  code_nest_ui: ^0.0.8



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # injectable generator 
  injectable_generator: ^2.7.0

  # json serializable 
  json_serializable: ^6.9.5

  # build runner 
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
