// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5mNMkD5Jemg-ZJxAk7_qsaUGqqOMNe1w',
    appId: '1:901150215905:android:afd9fca926badf6aa4b1a0',
    messagingSenderId: '901150215905',
    projectId: 'nfcreaderwriterapp',
    storageBucket: 'nfcreaderwriterapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfWkBRwNxsqoPeIKbVEtGEI5PzIJkXJjY',
    appId: '1:901150215905:ios:993a4cbf3d26217ba4b1a0',
    messagingSenderId: '901150215905',
    projectId: 'nfcreaderwriterapp',
    storageBucket: 'nfcreaderwriterapp.firebasestorage.app',
    androidClientId: '901150215905-0tmk4vdp899p3vgjoof109d9bo91rq3q.apps.googleusercontent.com',
    iosClientId: '901150215905-8e6gq0amnb52d0upqo073vm9ec41dnio.apps.googleusercontent.com',
    iosBundleId: 'com.example.postCleanArch',
  );
}
